### ISSUE TITLE
Issue with headless mode

### ISSUE THREAD

**Issue by felipemullen** [Fractural/GDTask#5] opened 2023-11-09 01:22 UTC
Hi, great library. I have been using it with success so far until recently after hitting a snag that I have not been able to figure out.

I have set up a minimal repository that implements the example in the main [Readme](/Readme.md), and it does not print any messages beyond the first awaited call:

https://github.com/felipemullen/gdtask-no-yield

Am I using something incorrectly? Or should we expect the awaits to work as presented in the readme?

**Comment by felipemullen** [comment] 2023-11-09 01:55
Actually I have found that the issue has to do with the `--headless` mode. Currently investigating

@Delsin-Yu you seem to have some deeper knowledge of this library. Do you have any ideas for why this could be happening?

**Comment by felipemullen** [comment] 2023-12-01 19:08
@Atlinx I believe I have found the heart of the issue. Throughout the code there are several uses of `Engine.GetFramesDrawn()`. In headless mode there are no frames drawn:

<img width="740" alt="Screenshot 2023-12-01 at 11 01 18 AM" src="https://github.com/Fractural/GDTask/assets/3488482/b4a26c27-7845-4862-aa90-910e2e5256e5">

Are you still maintaining this repository? I can open a pull request if you are.

**Comment by Atlinx** [comment] 2023-12-01 19:10
@felipemullen thanks for taking the time to finding the cause of the issue! Feel free to make a PR, I really appreciate your help :)

**Comment by Delsin-Yu** [comment] 2023-12-05 04:13
> Actually I have found that the issue has to do with the `--headless` mode. Currently investigating
> 
> @Delsin-Yu you seem to have some deeper knowledge of this library. Do you have any ideas for why this could be happening?

I think `Engine.GetProcessFrames` might be the API we should have used here.
I will submit a PR if this works.
![image](https://github.com/Fractural/GDTask/assets/71481700/db4a16ea-2e3f-45b7-992e-0677ac5e466d)

**Comment by Atlinx** [comment] 2023-12-30 23:28
Fixed by #6

**Closed as completed by Atlinx** 2023-12-30 23:28 UTC
